service: serverless-typescript-express-starter

frameworkVersion: '3'

custom:
  serverless-offline:
    httpPort: ${env:PORT, '8000'}
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  environment:
    NODE_OPTIONS: '--enable-source-maps'
  logs:
    http: true

functions:
  example:
    handler: src/functions/example/index.default
    events:
      - http:
          path: /example
          method: GET

plugins:
  - serverless-plugin-typescript
  - serverless-offline

